"""add_unique_constraint_to_port_number

Revision ID: 4773b380976c
Revises: 48bfa881a402
Create Date: 2026-05-02 22:49:46.009940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4773b380976c'
down_revision: Union[str, Sequence[str], None] = '48bfa881a402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device_ports', ['port_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_ports', type_='unique')
    # ### end Alembic commands ###
