"""create_device_ports_table and ip column

Revision ID: 48bfa881a402
Revises: f8c2d9e3a1b4
Create Date: 2026-05-02 22:31:31.213757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bfa881a402'
down_revision: Union[str, Sequence[str], None] = 'f8c2d9e3a1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('ip', sa.String(), nullable=True))
    op.alter_column('devices', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint(None, 'devices', ['ip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.alter_column('devices', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('devices', 'ip')
    op.drop_table('device_ports')
    # ### end Alembic commands ###
