"""Created notification model

Revision ID: 5cbbd0759406
Revises: e96141289d25
Create Date: 2026-03-15 20:32:27.637778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbbd0759406'
down_revision: Union[str, Sequence[str], None] = 'e96141289d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_managers_department'), 'department_managers', ['department'], unique=False)
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_column('employees', 'department')
    op.drop_index(op.f('ix_department_managers_department'), table_name='department_managers')
    op.drop_table('department_managers')
    # ### end Alembic commands ###
