"""adde new status table

Revision ID: 65f13e9bb6b6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-07 19:18:21.376987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f13e9bb6b6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_statuses', sa.Column('name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_device_statuses_device_id'), table_name='device_statuses')
    op.create_unique_constraint(None, 'device_statuses', ['name'])
    op.drop_constraint(op.f('device_statuses_device_id_fkey'), 'device_statuses', type_='foreignkey')
    op.drop_column('device_statuses', 'device_id')
    op.drop_column('device_statuses', 'status')
    op.add_column('devices', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'device_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'status_id')
    op.add_column('device_statuses', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('device_statuses', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('device_statuses_device_id_fkey'), 'device_statuses', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'device_statuses', type_='unique')
    op.create_index(op.f('ix_device_statuses_device_id'), 'device_statuses', ['device_id'], unique=False)
    op.drop_column('device_statuses', 'name')
    # ### end Alembic commands ###
