"""Added enable status for device

Revision ID: 73b287d80b50
Revises: 5cbbd0759406
Create Date: 2026-03-21 22:19:32.532081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b287d80b50'
down_revision: Union[str, Sequence[str], None] = '5cbbd0759406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'devices',
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true())
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'enabled')
    # ### end Alembic commands ###
