"""Added expited time for temporary employee

Revision ID: 7d65862e7068
Revises: 3789152b9908
Create Date: 2026-05-30 23:33:21.514634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d65862e7068'
down_revision: Union[str, Sequence[str], None] = '3789152b9908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('expired', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('guests', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('system_config', sa.Column('temporary_card_duration_hours', sa.Integer(), nullable=False, server_default='72'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'temporary_card_duration_hours')
    op.drop_column('guests', 'last_used_at')
    op.drop_column('employees', 'expired')
    # ### end Alembic commands ###
