"""Added login employoee

Revision ID: a2cb92aa8480
Revises: be0ecb812f0f
Create Date: 2026-01-30 10:46:47.263317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cb92aa8480'
down_revision: Union[str, Sequence[str], None] = 'be0ecb812f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('wms_login', sa.String(), nullable=True))
    op.create_index(op.f('ix_employees_wms_login'), 'employees', ['wms_login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_wms_login'), table_name='employees')
    op.drop_column('employees', 'wms_login')
    # ### end Alembic commands ###
