"""employee devices relationship

Revision ID: e654b0cebfc1
Revises: 26704f9c27ef
Create Date: 2026-01-07 22:13:27.415615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e654b0cebfc1'
down_revision: Union[str, Sequence[str], None] = '26704f9c27ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('employees_device_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_device_id_fkey'), 'employees', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'employee_id')
    # ### end Alembic commands ###
