"""Add system configuration table

Revision ID: f8c2d9e3a1b4
Revises: 73b287d80b50
Create Date: 2026-04-06 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c2d9e3a1b4'
down_revision: Union[str, Sequence[str], None] = '73b287d80b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token_expire_minutes', sa.Integer(), nullable=False),
    sa.Column('device_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('registration_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('device_cleanup_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('auth_cleanup_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('device_not_returned_hours', sa.Integer(), nullable=False),
    sa.Column('allow_registration_without_login', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
